Fix bugs and Add UI-Test
vfa-cancc/NCMB-Unity-Sample pull request #1
Opened 2021-09-16 02:43 UTC by vfa-cancc

2021-10-15 06:02 UTC, KokoroTanaka29 requested changes

2021-10-15 06:02 UTC, KokoroTanaka29 commented on Assets/PlayModeTests/UITestUser.cs
> +        ifUsername.text = "testuser";
こちらのusernameですが、他のアプリと統一するためuser_test1に変更をお願いいたします。

2021-10-18 02:52 UTC, vfa-trucldt commented on Assets/PlayModeTests/UITestUser.cs
> +        ifUsername.text = "testuser";
Tên name, thống nhất với những app khác là user_test1

2021-10-19 02:48 UTC, vfa-trucldt commented on Assets/PlayModeTests/UITestUser.cs
> +        ifUsername.text = "testuser";
対応済み

2021-10-19 04:54 UTC, KokoroTanaka29 approved these changes
ご対応いただきありがとうございます。
こちらマージいたします

2021-10-29 02:07 UTC, merged